In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_excel('../input/Career.xlsx')
data.describe(include='all')

,college,year,stream,cgpa,12th,10th,career,parents,income,locality,state
count,338,338,338,338,338,338,338,338,338,338,338
unique,5,4,13,3,2,2,6,5,4,2,19
top,IIITs,1st,"Computer science and engineering,",6-8,Private School,Private School,Public Sector Job,Public Sector,3-6 lakhs,Urban,Rajasthan
freq,133,104,123,185,237,243,132,150,96,232,142

In [3]:
from sklearn.preprocessing import LabelEncoder
data.college = data.college.astype('category') #.map({'IITs':0,'NITs':1,'IIITs':2,'Private':3,'Government':4})
data.year = data.year.astype('category') #.map({'1st':1,'2nd':2,'3rd':3,'4th':4})
data.stream = data.stream.map(
                {'Computer science and engineering,':1,'Electronics and communication engineering,':2,
                 'Information technology,':3,'Mechanical engineering,':4,'Civil engineering,':5,
                 'Mechatronics engineering,':6,'Electrical and electronics and engineering':7,
                 'Environmental engineering,':8,'Architecture and construction engineering,':9,
                 'Highway engineering,':10,'Computer engineering,':11,'Marine engineering,':12,
                 'Automobile engineering,':13,'Aeronautical engineering,':14,'Aerospace engineering,':15,
                 'Telecommunication engineering,':16,'Electronics and communication engineering,':17,
                 'Agricultural engineering,':18,'Production and industrial engineering,':19,
                 'Chemical engineering,':20,'Electrical engineering,':21,'Instrumental engineering,':22,
                 'Mining engineering,':23,'Architectural':24,'Biological Science':25,'Bio-Medical':26,
                 'Biological engineering':27,'Nuclear engineering':28,'Systems engineering':29,'Others':-1
                })
data.cgpa = data.cgpa.astype('category') #.map({'<6':0,'6-8':1,'>8':2})
data['12th'] = data['12th'].astype('category') #.map({'Private School':0,'Public School':1})
data['10th'] = data['10th'].astype('category') #.map({'Private School':0,'Public School':1})
data.career = data.career.astype('category') #.map({'Public Sector Job':0,'Private Sector job':1,'Defence':2,'Higher study':3,'Entrepreneurship':4,
#                 'Family business':5})
data.parents = data.parents.astype('category') #.map({'Business':0,'Public Sector':1,'Private Sector':2,'Defence':2,'Self-Employed':3})
data.income = data.income.astype('category') #.map({'< 3 lakhs':0,'3-6 lakhs':1,'6-10 lakhs':2,'> 10 lakhs':3})
stateEncoder = LabelEncoder().fit(['Rajasthan','Delhi','Haryana','Punjab','Chandigarh','Andhra Pradesh','Telangana',
                                   'Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat',
                                   'Himachal Pradesh','Jammu and Kashmir','Jharkhand','Karnataka','Kerala',
                                   'Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland',
                                   'Odisha','Sikkim','Tamil Nadu','Tripura','Uttar Pradesh','Uttarakhand',
                                   'West Bengal','Andaman and Nicobar Islands','Dadra and Nagar Haveli',
                                   'Daman and Diu','Lakshadweep','Pondicherry','Abroad'
                                  ])
data.state = stateEncoder.transform(data.state)
data.locality = data.locality.astype('category') #.map({'Rural':0,'Urban':1})

In [4]:
data.head()

,college,year,stream,cgpa,12th,10th,career,parents,income,locality,state
0,IIITs,2nd,1,<6,Private School,Private School,Higher study,Public Sector,> 10 lakhs,Urban,29
1,Government,4th,20,6-8,Private School,Private School,Public Sector Job,Public Sector,3-6 lakhs,Urban,13
2,NITs,4th,5,6-8,Private School,Private School,Public Sector Job,Self-Employed,< 3 lakhs,Rural,29
3,Government,4th,17,6-8,Private School,Private School,Entrepreneurship,Public Sector,> 10 lakhs,Urban,10
4,Private,3rd,3,6-8,Private School,Private School,Private Sector job,Business,3-6 lakhs,Urban,34

In [20]:
print(data.college.value_counts())
pd.crosstab(data.college, data.career,normalize='index').style.background_gradient(cmap='autumn_r')

IIITs         133
NITs          109
Government     48
Private        42
IITs            6
Name: college, dtype: int64

In [19]:
print(data.year.value_counts())
pd.crosstab(data.year, data.career,normalize='index').style.background_gradient(cmap='autumn_r')

1st    104
4th     97
3rd     81
2nd     56
Name: year, dtype: int64

In [21]:
print(data.cgpa.value_counts())
pd.crosstab(data.cgpa, data.career,normalize='index').style.background_gradient(cmap='autumn_r')

6-8    185
>8     128
<6      25
Name: cgpa, dtype: int64

In [22]:
print(data.parents.value_counts())
pd.crosstab(data.parents, data.career,normalize='index').style.background_gradient(cmap='autumn_r')

Public Sector     150
Self-Employed      73
Private Sector     51
Business           49
Defence            15
Name: parents, dtype: int64

In [23]:
print(data.income.value_counts())
pd.crosstab(data.income, data.career,normalize='index').style.background_gradient(cmap='autumn_r')

3-6 lakhs     96
< 3 lakhs     92
6-10 lakhs    81
> 10 lakhs    69
Name: income, dtype: int64

In [24]:
print(data.locality.value_counts())
pd.crosstab(data.locality, data.career,normalize='index').style.background_gradient(cmap='autumn_r')

Urban    232
Rural    106
Name: locality, dtype: int64

In [25]:
print(data.stream.value_counts())

 1     123
 17     89
 4      33
 21     25
 5      17
 3      16
 20     10
-1      10
 7       7
 11      4
 19      2
 27      1
 23      1
Name: stream, dtype: int64